### create a new expense by user 1
POST http://localhost:8080/api/v1/users/1/expenses
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsImlhdCI6MTcxNDA2OTA2OCwiZXhwIjoxNzE0MDcyNjY4fQ.pEr4AdwZuo7g-sme8pkbn1hrEnSM_8_gh-0EQX8xT1I7kfy9qutaBtJNsyIfugYmk0XK5-uXP3dWgZA0bdMQyw
Content-Type: application/json

{
  "name": "Jan Rent",
  "description": "rent for Jan 2024",
  "amount": 1100,
  "paymentDate": "2024-01-01",
  "category": {
    "name": "Rent"
  }
}

### get all expenses by user 1
GET http://localhost:8080/api/v1/users/1/expenses
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsImlhdCI6MTcxNDA2OTA2OCwiZXhwIjoxNzE0MDcyNjY4fQ.pEr4AdwZuo7g-sme8pkbn1hrEnSM_8_gh-0EQX8xT1I7kfy9qutaBtJNsyIfugYmk0XK5-uXP3dWgZA0bdMQyw

### get all expenses with category 'Rent' by user 1
GET http://localhost:8080/api/v1/users/1/expenses?category=Rent
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsImlhdCI6MTcxNDA2OTA2OCwiZXhwIjoxNzE0MDcyNjY4fQ.pEr4AdwZuo7g-sme8pkbn1hrEnSM_8_gh-0EQX8xT1I7kfy9qutaBtJNsyIfugYmk0XK5-uXP3dWgZA0bdMQyw

### get expense 1 by user 1
GET http://localhost:8080/api/v1/users/1/expenses/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsImlhdCI6MTcxNDA2OTA2OCwiZXhwIjoxNzE0MDcyNjY4fQ.pEr4AdwZuo7g-sme8pkbn1hrEnSM_8_gh-0EQX8xT1I7kfy9qutaBtJNsyIfugYmk0XK5-uXP3dWgZA0bdMQyw

### update expense 1 by user 1
PUT http://localhost:8080/api/v1/users/1/expenses/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsImlhdCI6MTcxNDA2OTA2OCwiZXhwIjoxNzE0MDcyNjY4fQ.pEr4AdwZuo7g-sme8pkbn1hrEnSM_8_gh-0EQX8xT1I7kfy9qutaBtJNsyIfugYmk0XK5-uXP3dWgZA0bdMQyw
Content-Type: application/json

{
  "name": "Jan Rent",
  "description": "rent for Jan 2024",
  "amount": 1200,
  "paymentDate": "2024-01-01",
  "category": {
    "name": "Monthly Rent"
  }
}

### delete expense 1 by user 1
DELETE http://localhost:8080/api/v1/users/1/expenses/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsImlhdCI6MTcxNDA2OTA2OCwiZXhwIjoxNzE0MDcyNjY4fQ.pEr4AdwZuo7g-sme8pkbn1hrEnSM_8_gh-0EQX8xT1I7kfy9qutaBtJNsyIfugYmk0XK5-uXP3dWgZA0bdMQyw
