### get all incomes by user 1
GET http://localhost:8080/api/v1/users/1/incomes
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYXNraUBnbWFpbC5jb20iLCJpYXQiOjE3MTMzMjk0MjcsImV4cCI6MTcxMzMzMzAyN30.94A6dArFLbbrYqS81WUGaXLvNHOh-_JGfy0hJzdRbM0SgA3k358om8E-ud4AOfOBIN-R8wcmPDNTEX6huYgXTw

### add a new income by user 1
POST http://localhost:8080/api/v1/users/1/incomes
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYXNraUBnbWFpbC5jb20iLCJpYXQiOjE3MTMzMjk0MjcsImV4cCI6MTcxMzMzMzAyN30.94A6dArFLbbrYqS81WUGaXLvNHOh-_JGfy0hJzdRbM0SgA3k358om8E-ud4AOfOBIN-R8wcmPDNTEX6huYgXTw
Content-Type: application/json

{
  "source": "full-time work",
  "amount": 3000
}

### get an income 1 by user 1
GET http://localhost:8080/api/v1/users/1/incomes/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYXNraUBnbWFpbC5jb20iLCJpYXQiOjE3MTMzMjk0MjcsImV4cCI6MTcxMzMzMzAyN30.94A6dArFLbbrYqS81WUGaXLvNHOh-_JGfy0hJzdRbM0SgA3k358om8E-ud4AOfOBIN-R8wcmPDNTEX6huYgXTw

### update an income 1 by user 1
PUT http://localhost:8080/api/v1/users/1/incomes/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYXNraUBnbWFpbC5jb20iLCJpYXQiOjE3MTMzMjk0MjcsImV4cCI6MTcxMzMzMzAyN30.94A6dArFLbbrYqS81WUGaXLvNHOh-_JGfy0hJzdRbM0SgA3k358om8E-ud4AOfOBIN-R8wcmPDNTEX6huYgXTw
Content-Type: application/json

{
  "source": "part time work",
  "amount": 2500,
  "active": false
}

### delete an income 1 by user 1
DELETE http://localhost:8080/api/v1/users/1/incomes/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYXNraUBnbWFpbC5jb20iLCJpYXQiOjE3MTMzMjk0MjcsImV4cCI6MTcxMzMzMzAyN30.94A6dArFLbbrYqS81WUGaXLvNHOh-_JGfy0hJzdRbM0SgA3k358om8E-ud4AOfOBIN-R8wcmPDNTEX6huYgXTw
